INSERT ALL
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (1, 'Easy')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (2, 'Moderate')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (3, 'Challenging')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (4, 'Hard')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (5, 'Extreme')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (6, 'Family Friendly')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (7, 'Beginner')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (8, 'Intermediate')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (9, 'Advanced')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (10, 'Expert')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (11, 'Toddler Safe')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (12, 'Senior Friendly')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (13, 'Technical')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (14, 'Professional')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (15, 'Level 1')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (16, 'Level 2')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (17, 'Level 3')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (18, 'Level 4')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (19, 'Level 5')
INTO DIFFICULTYLEVEL (DifficultyID, DifficultyName) VALUES (20, 'Master')
SELECT * FROM dual;

INSERT ALL
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (1, 'Scheduled')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (2, 'Confirmed')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (3, 'In Progress')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (4, 'Completed')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (5, 'Cancelled')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (6, 'Postponed')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (7, 'Fully Booked')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (8, 'Pending')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (9, 'Draft')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (10, 'On Hold')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (11, 'Awaiting Guide')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (12, 'Closed')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (13, 'Archived')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (14, 'Sold Out')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (15, 'Maintenance')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (16, 'Hidden')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (17, 'Available')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (18, 'Last Minute')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (19, 'Premium Only')
INTO TOURSTATUS (TourStatusID, StatusName) VALUES (20, 'Returning Soon')
SELECT * FROM dual;

INSERT ALL
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (1, 'Registered')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (2, 'Confirmed')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (3, 'Waitlist')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (4, 'Cancelled')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (5, 'Refunded')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (6, 'No Show')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (7, 'Pending Payment')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (8, 'Partial Deposit')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (9, 'Interested')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (10, 'Invitation Sent')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (11, 'Approved')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (12, 'Rejected')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (13, 'Expired')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (14, 'Review Needed')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (15, 'Rebooked')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (16, 'Group Hold')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (17, 'Completed')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (18, 'VIP Pending')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (19, 'Voucher Used')
INTO REGISTRATIONSTATUS (RegistrationStatusID, StatusName) VALUES (20, 'Locked')
SELECT * FROM dual;


INSERT ALL
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (1, 'Unpaid')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (2, 'Partial')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (3, 'Paid In Full')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (4, 'Refunded')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (5, 'Declined')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (6, 'Processing')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (7, 'Voided')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (8, 'Chargeback')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (9, 'Authorized')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (10, 'Cash Pending')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (11, 'Bank Transfer Sent')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (12, 'Overpaid')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (13, 'Awaiting Verification')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (14, 'Credit Issued')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (15, 'Bad Debt')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (16, 'Written Off')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (17, 'Disputed')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (18, 'Installments')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (19, 'Gift Card')
INTO PAYMENTSTATUS (PaymentStatusID, StatusName) VALUES (20, 'Comped')
SELECT * FROM dual;


INSERT ALL
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (1, 'Yossi', 'Cohen', '050-1111111', 'yossi@gmail.com', TO_DATE('1985-05-10', 'YYYY-MM-DD'), TO_DATE('2015-01-01', 'YYYY-MM-DD'), 500.00, 10, 4.8)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (2, 'Michal', 'Levi', '050-2222222', 'michal@gmail.com', TO_DATE('1990-03-15', 'YYYY-MM-DD'), TO_DATE('2018-06-12', 'YYYY-MM-DD'), 450.00, 6, 4.5)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (3, 'David', 'Israeli', '050-3333333', 'david@gmail.com', TO_DATE('1978-11-20', 'YYYY-MM-DD'), TO_DATE('2010-02-25', 'YYYY-MM-DD'), 600.00, 15, 5.0)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (4, 'Sarah', 'Blau', '050-4444444', 'sarah@gmail.com', TO_DATE('1992-07-30', 'YYYY-MM-DD'), TO_DATE('2020-09-01', 'YYYY-MM-DD'), 400.00, 3, 4.2)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (5, 'Ron', 'Shahar', '050-5555555', 'ron@gmail.com', TO_DATE('1988-01-05', 'YYYY-MM-DD'), TO_DATE('2016-04-10', 'YYYY-MM-DD'), 520.00, 8, 4.7)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (6, 'Dana', 'Tal', '050-6666666', 'dana@gmail.com', TO_DATE('1995-12-12', 'YYYY-MM-DD'), TO_DATE('2021-01-15', 'YYYY-MM-DD'), 380.00, 2, 4.0)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (7, 'Avi', 'Mizrahi', '050-7777777', 'avi@gmail.com', TO_DATE('1982-08-08', 'YYYY-MM-DD'), TO_DATE('2012-05-05', 'YYYY-MM-DD'), 550.00, 12, 4.9)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (8, 'Noa', 'Katz', '050-8888888', 'noa@gmail.com', TO_DATE('1991-04-22', 'YYYY-MM-DD'), TO_DATE('2019-02-28', 'YYYY-MM-DD'), 430.00, 5, 4.4)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (9, 'Itay', 'Barak', '050-9999999', 'itay@gmail.com', TO_DATE('1980-02-14', 'YYYY-MM-DD'), TO_DATE('2011-11-11', 'YYYY-MM-DD'), 580.00, 13, 4.8)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (10, 'Maya', 'Golan', '052-1111111', 'maya@gmail.com', TO_DATE('1993-10-10', 'YYYY-MM-DD'), TO_DATE('2022-03-01', 'YYYY-MM-DD'), 350.00, 1, 3.9)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (11, 'Erez', 'Harel', '052-2222222', 'erez@gmail.com', TO_DATE('1984-06-06', 'YYYY-MM-DD'), TO_DATE('2014-07-07', 'YYYY-MM-DD'), 510.00, 10, 4.6)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (12, 'Adi', 'Friedman', '052-3333333', 'adi@gmail.com', TO_DATE('1989-09-09', 'YYYY-MM-DD'), TO_DATE('2017-08-08', 'YYYY-MM-DD'), 470.00, 7, 4.5)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (13, 'Omer', 'Dahan', '052-4444444', 'omer@gmail.com', TO_DATE('1986-05-25', 'YYYY-MM-DD'), TO_DATE('2015-12-12', 'YYYY-MM-DD'), 490.00, 9, 4.3)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (14, 'Gal', 'Avni', '052-5555555', 'gal@gmail.com', TO_DATE('1994-01-20', 'YYYY-MM-DD'), TO_DATE('2020-05-05', 'YYYY-MM-DD'), 410.00, 4, 4.1)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (15, 'Amit', 'Sela', '052-6666666', 'amit@gmail.com', TO_DATE('1981-12-30', 'YYYY-MM-DD'), TO_DATE('2013-02-02', 'YYYY-MM-DD'), 560.00, 11, 4.9)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (16, 'Shir', 'Agmon', '052-7777777', 'shir@gmail.com', TO_DATE('1996-03-03', 'YYYY-MM-DD'), TO_DATE('2022-11-11', 'YYYY-MM-DD'), 360.00, 1, 4.0)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (17, 'Nir', 'Bassan', '052-8888888', 'nir@gmail.com', TO_DATE('1975-04-18', 'YYYY-MM-DD'), TO_DATE('2005-06-01', 'YYYY-MM-DD'), 700.00, 20, 5.0)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (18, 'Liat', 'Ziv', '052-9999999', 'liat@gmail.com', TO_DATE('1987-07-07', 'YYYY-MM-DD'), TO_DATE('2016-10-10', 'YYYY-MM-DD'), 500.00, 8, 4.6)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (19, 'Tomer', 'Ben-Ari', '053-1111111', 'tomer@gmail.com', TO_DATE('1990-08-15', 'YYYY-MM-DD'), TO_DATE('2018-01-01', 'YYYY-MM-DD'), 440.00, 6, 4.4)
INTO GUIDE (GuideID, FirstName, LastName, Phone, Email, BirthDate, JoinDate, DailyRate, ExperienceYears, Rating)
VALUES (20, 'Roni', 'Erez', '053-2222222', 'roni@gmail.com', TO_DATE('1993-02-02', 'YYYY-MM-DD'), TO_DATE('2021-09-09', 'YYYY-MM-DD'), 390.00, 3, 4.2)
SELECT * FROM dual;


INSERT ALL
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (1, 'Masada Sunrise', 5.5, 180, 4)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (2, 'Nahal Arugot', 4.0, 120, 2)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (3, 'Mount Carmel Forest', 10.2, 240, 3)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (4, 'Tel Aviv Urban Walk', 3.0, 90, 1)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (5, 'Eilat Red Canyon', 2.5, 60, 2)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (6, 'Golan Heights Trail', 15.0, 360, 5)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (7, 'Jerusalem Old City', 2.0, 120, 1)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (8, 'Ein Gedi Waterfall', 1.5, 45, 1)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (9, 'Arbel Cliff Hike', 4.5, 150, 4)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (10, 'Mount Tabor Loop', 7.0, 200, 3)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (11, 'Banias River Walk', 3.5, 100, 2)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (12, 'Makhtesh Ramon Rim', 12.0, 300, 4)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (13, 'Agamon Hula Birding', 8.0, 180, 1)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (14, 'Nahal Kziv', 6.0, 180, 3)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (15, 'Sataf Spring Trail', 3.0, 90, 2)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (16, 'Mount Hermon Summit', 5.0, 210, 5)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (17, 'Caesarea Ruins', 2.0, 60, 1)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (18, 'Yehiam Fortress Hike', 4.0, 120, 2)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (19, 'Nahal Alexander', 5.0, 120, 1)
INTO ROUTE (RouteID, Name, EstimatedLength, EstimatedDuration, DifficultyID) VALUES (20, 'Mount Meron Peak', 9.0, 240, 3)
SELECT * FROM dual;


INSERT ALL
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (1, TO_DATE('2024-05-01', 'YYYY-MM-DD'), 'Masada Entrance', 150.00, 20, 1, 1, 1)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (2, TO_DATE('2024-05-05', 'YYYY-MM-DD'), 'Ein Gedi Parking', 120.00, 15, 1, 2, 2)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (3, TO_DATE('2024-05-10', 'YYYY-MM-DD'), 'Haifa University', 100.00, 25, 1, 3, 3)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (4, TO_DATE('2024-05-12', 'YYYY-MM-DD'), 'Habima Square', 80.00, 30, 1, 4, 4)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (5, TO_DATE('2024-05-15', 'YYYY-MM-DD'), 'Eilat Canyon Site', 200.00, 10, 1, 5, 5)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (6, TO_DATE('2024-06-01', 'YYYY-MM-DD'), 'Majdal Shams', 250.00, 12, 1, 6, 6)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (7, TO_DATE('2024-06-02', 'YYYY-MM-DD'), 'Jaffa Gate', 90.00, 40, 1, 7, 7)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (8, TO_DATE('2024-06-03', 'YYYY-MM-DD'), 'Ein Gedi Kiosk', 110.00, 20, 1, 8, 8)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (9, TO_DATE('2024-06-05', 'YYYY-MM-DD'), 'Migdal Village', 140.00, 15, 1, 9, 9)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (10, TO_DATE('2024-06-07', 'YYYY-MM-DD'), 'Mount Tabor Base', 130.00, 18, 1, 10, 10)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (11, TO_DATE('2024-06-10', 'YYYY-MM-DD'), 'Banias Springs', 115.00, 22, 1, 11, 11)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (12, TO_DATE('2024-06-15', 'YYYY-MM-DD'), 'Visitor Center Ramon', 180.00, 14, 1, 12, 12)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (13, TO_DATE('2024-06-20', 'YYYY-MM-DD'), 'Hula Main Gate', 95.00, 35, 1, 13, 13)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (14, TO_DATE('2024-06-25', 'YYYY-MM-DD'), 'Mitzpe Hila', 160.00, 20, 1, 14, 14)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (15, TO_DATE('2024-07-01', 'YYYY-MM-DD'), 'Sataf Parking', 105.00, 25, 1, 15, 15)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (16, TO_DATE('2024-07-05', 'YYYY-MM-DD'), 'Hermon Lower Base', 300.00, 8, 1, 16, 16)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (17, TO_DATE('2024-07-10', 'YYYY-MM-DD'), 'National Park Entrance', 125.00, 30, 1, 17, 17)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (18, TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'Kibbutz Yehiam', 135.00, 15, 1, 18, 18)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (19, TO_DATE('2024-07-20', 'YYYY-MM-DD'), 'Turtle Bridge', 85.00, 40, 1, 19, 19)
INTO GUIDEDTOUR (TourID, StartDate, MeetingPoint, Price, MaxParticipants, TourStatusID, GuideID, RouteID)
VALUES (20, TO_DATE('2024-07-25', 'YYYY-MM-DD'), 'Beit Jann', 155.00, 18, 1, 20, 20)
SELECT * FROM dual;



INSERT ALL
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (1, 'Moshe Levi', '054-1234567', 'moshe@gmail.com', TO_DATE('2023-01-10', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (2, 'Rivka Dayan', '054-2345678', 'rivka@gmail.com', TO_DATE('2023-02-15', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (3, 'Yosi Amar', '054-3456789', 'yosi_a@gmail.com', TO_DATE('2023-03-20', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (4, 'Liora Peretz', '054-4567890', 'liora@gmail.com', TO_DATE('2023-04-05', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (5, 'Eyal Biton', '054-5678901', 'eyal@gmail.com', TO_DATE('2023-05-12', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (6, 'Dorit Gabbay', '054-6789012', 'dorit@gmail.com', TO_DATE('2023-06-18', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (7, 'Sharon Sabag', '054-7890123', 'sharon@gmail.com', TO_DATE('2023-07-22', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (8, 'Guy Ohayon', '054-8901234', 'guy@gmail.com', TO_DATE('2023-08-30', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (9, 'Tali Vaknin', '054-9012345', 'tali@gmail.com', TO_DATE('2023-09-14', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (10, 'Ben Hazan', '054-0123456', 'ben@gmail.com', TO_DATE('2023-10-10', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (11, 'Orit Elbaz', '058-1111111', 'orit@gmail.com', TO_DATE('2023-11-11', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (12, 'Ilan Melamed', '058-2222222', 'ilan@gmail.com', TO_DATE('2023-12-01', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (13, 'Hila Naveh', '058-3333333', 'hila@gmail.com', TO_DATE('2024-01-05', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (14, 'Niv Golan', '058-4444444', 'niv@gmail.com', TO_DATE('2024-01-20', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (15, 'Sapir Shani', '058-5555555', 'sapir@gmail.com', TO_DATE('2024-02-10', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (16, 'Roei Sagy', '058-6666666', 'roei@gmail.com', TO_DATE('2024-02-15', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (17, 'Maya Roz', '058-7777777', 'maya_r@gmail.com', TO_DATE('2024-02-28', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (18, 'Dan Arad', '058-8888888', 'dan@gmail.com', TO_DATE('2024-03-01', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (19, 'Ziv Alon', '058-9999999', 'ziv@gmail.com', TO_DATE('2024-03-05', 'YYYY-MM-DD'))
INTO CUSTOMER (CustomerID, FullName, Phone, Email, JoinDate) VALUES (20, 'Gali Koren', '053-3333333', 'gali@gmail.com', TO_DATE('2024-03-10', 'YYYY-MM-DD'))
SELECT * FROM dual;



INSERT ALL
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (1, TO_DATE('2024-04-01', 'YYYY-MM-DD'), 150.00, 1, 2, 1)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (2, TO_DATE('2024-04-02', 'YYYY-MM-DD'), 120.00, 2, 2, 2)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (3, TO_DATE('2024-04-03', 'YYYY-MM-DD'), 100.00, 3, 2, 3)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (4, TO_DATE('2024-04-04', 'YYYY-MM-DD'), 80.00, 4, 1, 4)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (5, TO_DATE('2024-04-05', 'YYYY-MM-DD'), 200.00, 5, 2, 5)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (6, TO_DATE('2024-04-10', 'YYYY-MM-DD'), 250.00, 6, 2, 6)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (7, TO_DATE('2024-04-11', 'YYYY-MM-DD'), 90.00, 7, 2, 7)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (8, TO_DATE('2024-04-12', 'YYYY-MM-DD'), 110.00, 8, 2, 8)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (9, TO_DATE('2024-04-15', 'YYYY-MM-DD'), 140.00, 9, 1, 9)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (10, TO_DATE('2024-04-16', 'YYYY-MM-DD'), 130.00, 10, 2, 10)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (11, TO_DATE('2024-04-17', 'YYYY-MM-DD'), 115.00, 11, 2, 11)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (12, TO_DATE('2024-04-18', 'YYYY-MM-DD'), 180.00, 12, 1, 12)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (13, TO_DATE('2024-04-19', 'YYYY-MM-DD'), 95.00, 13, 2, 13)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (14, TO_DATE('2024-04-20', 'YYYY-MM-DD'), 160.00, 14, 2, 14)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (15, TO_DATE('2024-04-21', 'YYYY-MM-DD'), 105.00, 15, 2, 15)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (16, TO_DATE('2024-04-22', 'YYYY-MM-DD'), 300.00, 16, 2, 16)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (17, TO_DATE('2024-04-23', 'YYYY-MM-DD'), 125.00, 17, 2, 17)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (18, TO_DATE('2024-04-24', 'YYYY-MM-DD'), 135.00, 18, 1, 18)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (19, TO_DATE('2024-04-25', 'YYYY-MM-DD'), 85.00, 19, 2, 19)
INTO REGISTRATION (RegistrationID, RegistrationDate, AmountToPay, TourID, RegistrationStatusID, CustomerID)
VALUES (20, TO_DATE('2024-04-26', 'YYYY-MM-DD'), 155.00, 20, 2, 20)
SELECT * FROM dual;



INSERT ALL
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (1, TO_DATE('2024-04-01', 'YYYY-MM-DD'), 150.00, 'Credit Card', 1, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (2, TO_DATE('2024-04-02', 'YYYY-MM-DD'), 120.00, 'PayPal', 2, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (3, TO_DATE('2024-04-03', 'YYYY-MM-DD'), 100.00, 'Cash', 3, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (4, TO_DATE('2024-04-04', 'YYYY-MM-DD'), 40.00, 'Credit Card', 4, 2)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (5, TO_DATE('2024-04-05', 'YYYY-MM-DD'), 200.00, 'Bank Transfer', 5, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (6, TO_DATE('2024-04-10', 'YYYY-MM-DD'), 250.00, 'Credit Card', 6, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (7, TO_DATE('2024-04-11', 'YYYY-MM-DD'), 90.00, 'PayPal', 7, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (8, TO_DATE('2024-04-12', 'YYYY-MM-DD'), 110.00, 'Cash', 8, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (9, TO_DATE('2024-04-15', 'YYYY-MM-DD'), 0.00, 'Credit Card', 9, 1)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (10, TO_DATE('2024-04-16', 'YYYY-MM-DD'), 130.00, 'Bank Transfer', 10, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (11, TO_DATE('2024-04-17', 'YYYY-MM-DD'), 115.00, 'Credit Card', 11, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (12, TO_DATE('2024-04-18', 'YYYY-MM-DD'), 0.00, 'PayPal', 12, 1)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (13, TO_DATE('2024-04-19', 'YYYY-MM-DD'), 95.00, 'Cash', 13, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (14, TO_DATE('2024-04-20', 'YYYY-MM-DD'), 160.00, 'Credit Card', 14, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (15, TO_DATE('2024-04-21', 'YYYY-MM-DD'), 105.00, 'PayPal', 15, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (16, TO_DATE('2024-04-22', 'YYYY-MM-DD'), 300.00, 'Bank Transfer', 16, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (17, TO_DATE('2024-04-23', 'YYYY-MM-DD'), 125.00, 'Credit Card', 17, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (18, TO_DATE('2024-04-24', 'YYYY-MM-DD'), 0.00, 'Cash', 18, 1)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (19, TO_DATE('2024-04-25', 'YYYY-MM-DD'), 85.00, 'Credit Card', 19, 3)
INTO PAYMENT (PaymentID, PaymentDate, Amount, PaymentMethod, RegistrationID, PaymentStatusID)
VALUES (20, TO_DATE('2024-04-26', 'YYYY-MM-DD'), 155.00, 'PayPal', 20, 3)
SELECT * FROM dual;