SELECT 'GUIDE' as Table_Name, COUNT(*) FROM GUIDE
UNION ALL
SELECT 'DIFFICULTYLEVEL', COUNT(*) FROM DIFFICULTYLEVEL
UNION ALL
SELECT 'ROUTE', COUNT(*) FROM ROUTE
UNION ALL
SELECT 'TOURSTATUS', COUNT(*) FROM TOURSTATUS
UNION ALL
SELECT 'GUIDEDTOUR', COUNT(*) FROM GUIDEDTOUR
UNION ALL
SELECT 'CUSTOMER', COUNT(*) FROM CUSTOMER
UNION ALL
SELECT 'REGISTRATIONSTATUS', COUNT(*) FROM REGISTRATIONSTATUS
UNION ALL
SELECT 'REGISTRATION', COUNT(*) FROM REGISTRATION
UNION ALL
SELECT 'PAYMENTSTATUS', COUNT(*) FROM PAYMENTSTATUS
UNION ALL
SELECT 'PAYMENT', COUNT(*) FROM PAYMENT;

SELECT * FROM GUIDE FETCH FIRST 10 ROWS ONLY;
SELECT * FROM DIFFICULTYLEVEL;
SELECT * FROM ROUTE FETCH FIRST 10 ROWS ONLY;
SELECT * FROM TOURSTATUS;
SELECT * FROM GUIDEDTOUR FETCH FIRST 10 ROWS ONLY;
SELECT * FROM CUSTOMER FETCH FIRST 10 ROWS ONLY;
SELECT * FROM REGISTRATIONSTATUS;
SELECT * FROM REGISTRATION FETCH FIRST 10 ROWS ONLY;
SELECT * FROM PAYMENTSTATUS;
SELECT * FROM PAYMENT FETCH FIRST 10 ROWS ONLY;

SELECT 
    R.RegistrationID, 
    C.FullName as Customer_Name, 
    T.StartDate as Tour_Date, 
    RS.StatusName as Reg_Status
FROM REGISTRATION R
JOIN CUSTOMER C ON R.CustomerID = C.CustomerID
JOIN GUIDEDTOUR T ON R.TourID = T.TourID
JOIN REGISTRATIONSTATUS RS ON R.RegistrationStatusID = RS.RegistrationStatusID
FETCH FIRST 20 ROWS ONLY;

SELECT 
    P.PaymentID, 
    P.Amount, 
    P.PaymentMethod, 
    PS.StatusName as Payment_Status,
    R.RegistrationID
FROM PAYMENT P
JOIN PAYMENTSTATUS PS ON P.PaymentStatusID = PS.PaymentStatusID
JOIN REGISTRATION R ON P.RegistrationID = R.RegistrationID
FETCH FIRST 20 ROWS ONLY;

SELECT 
    T.TourID, 
    T.MeetingPoint, 
    G.FirstName || ' ' || G.LastName as Guide_Name, 
    RT.Name as Route_Name
FROM GUIDEDTOUR T
JOIN GUIDE G ON T.GuideID = G.GuideID
JOIN ROUTE RT ON T.RouteID = RT.RouteID
FETCH FIRST 20 ROWS ONLY;